force-app/main/default/objects/DefaultCommunityProfile__c/DefaultCommunityProfile__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Profiles to be used in communities</description>
    <label>Default Community Profile</label>
</CustomObject>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/PersonAccountDefaultProfile__c.field-meta.xml
<CustomField>
    <fullName>PersonAccountDefaultProfile__c</fullName>
    <description>Communities for person account users</description>
    <label>Person Account Default Profile</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CommunityUsersService.cls
public with sharing class CommunityUsersService {

    public static User getOrCreatePersonAccountUser(String nationalIdentityNumber) {
        List<User> existingUsers = new UsersSelector().selectByAccountIdent(new Set<String>{
                nationalIdentityNumber
        });
        if (existingUsers.size() > 0) return existingUsers[0];

        DefaultCommunityProfile__c defaultCommunityProfiles=DefaultCommunityProfile__c.getOrgDefaults();
        String profileName = defaultCommunityProfiles.PersonAccountDefaultProfile__c;
        Profile profile = [SELECT Id FROM Profile WHERE Name = :profileName];
        List<Account> personAccounts=new PersonAccountsSelector().selectByIdent(new Set<String>{nationalIdentityNumber});

        if (personAccounts.size()>0 && profile != null) {
            ContactWrapper contact=new ContactWrapper(personAccounts[0]);
            return new Users().createCommunityUser(contact, profile.Id);
        }

        return null;
    }
}