force-app/main/default/objects/DefaultCommunityProfile__c/DefaultCommunityProfile__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Profiles to be used in communities</description>
    <label>Default Community Profile</label>
</CustomObject>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/DefaultCommunityPlusLoginCommunityId__c.field-meta.xml
<CustomField>
    <fullName>DefaultCommunityPlusLoginCommunityId__c</fullName>
    <label>Default Community Plus Login CommunityId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/DefaultCommunityPlusLoginPermSet__c.field-meta.xml
<CustomField>
    <fullName>DefaultCommunityPlusLoginPermSet__c</fullName>
    <label>Default Community Plus Login Perm Set</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/DefaultCommunityPlusLoginProfile__c.field-meta.xml
<CustomField>
    <fullName>DefaultCommunityPlusLoginProfile__c</fullName>
    <label>Default Community Plus Login Profile</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/DefaultCommunityPlusPermissionSetGroup__c.field-meta.xml
<CustomField>
    <fullName>DefaultCommunityPlusPermissionSetGroup__c</fullName>
    <label>Default Community Plus Perm. Set Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/DefaultCommunityPlusProfile__c.field-meta.xml
<CustomField>
    <fullName>DefaultCommunityPlusProfile__c</fullName>
    <label>Default Community Plus Profile</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/DefaultPermissionSet__c.field-meta.xml
<CustomField>
    <fullName>DefaultPermissionSet__c</fullName>
    <label>Default Permission Set</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/DefaultProfile__c.field-meta.xml
<CustomField>
    <fullName>DefaultProfile__c</fullName>
    <label>Default Profile</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestUserSelfRegHandler_Test.cls
@IsTest
private class TestUserSelfRegHandler_Test {

    @TestSetup
    private static void makeData(){
        Profile communityProfile = [
            SELECT Name
            FROM Profile
            WHERE Name = 'Personbruker Login' OR Name = 'Trial Customer Portal User'
            LIMIT 1
        ];

        Profile communityPlusLoginProfile = [
            SELECT Name
            FROM Profile
            WHERE Name = 'Samhandler Login' OR Name = 'Trial Customer Portal User'
            LIMIT 1
        ];

        DefaultCommunityProfile__c defaultCommunityProfile = new DefaultCommunityProfile__c(
            DefaultProfile__c = communityProfile.Name,
            DefaultPermissionSet__c = 'CRM_ManageAsyncRequests',
            DefaultCommunityPlusProfile__c = 'Trial Customer Portal User',
            DefaultCommunityPlusPermissionSetGroup__c = 'Test',
            DefaultCommunityPlusLoginPermSet__c='TestCommunity',
            DefaultCommunityPlusLoginProfile__c=communityPlusLoginProfile.Name,
            DefaultCommunityPlusLoginCommunityId__c='123'
        );
        insert defaultCommunityProfile;
    }

    @IsTest
    private static void createUser() {
        User navEmployee = TestDataFactory_Community.getUsers(1, 'System Administrator', true, true)[0];
        System.runAs(navEmployee) {
            Account personAccount = TestDataFactory_Community.getPersonAccounts(1)[0];

            Map<SObjectField, String> registrationAttributes=new  Map<SObjectField, String>();
            Schema.DescribeFieldResult fn = user.firstname.getDescribe();
            Schema.sObjectField fname = fn.getSObjectField();
            registrationAttributes.put(fname, '1');
            

            Test.startTest();
            TestUserSelfRegHandler regHandler = new TestUserSelfRegHandler();
            Id userId = regHandler.createUser(null, null,registrationAttributes,'P8ssword');
            Test.stopTest();
            System.assert(userId != null);

            System.assertEquals(1, [SELECT COUNT() FROM User WHERE Id=:userId],'Expect one user to be created');
        }
    }

}