force-app/main/default/objects/DefaultCommunityProfile__c/DefaultCommunityProfile__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Profiles to be used in communities</description>
    <label>Default Community Profile</label>
</CustomObject>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/DefaultCommunityPlusLoginPermSet__c.field-meta.xml
<CustomField>
    <fullName>DefaultCommunityPlusLoginPermSet__c</fullName>
    <label>Default Community Plus Login Perm Set</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/DefaultCommunityPlusLoginProfile__c.field-meta.xml
<CustomField>
    <fullName>DefaultCommunityPlusLoginProfile__c</fullName>
    <label>Default Community Plus Login Profile</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/DefaultCommunityPlusPermissionSetGroup__c.field-meta.xml
<CustomField>
    <fullName>DefaultCommunityPlusPermissionSetGroup__c</fullName>
    <label>Default Community Plus Perm. Set Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/DefaultCommunityPlusProfile__c.field-meta.xml
<CustomField>
    <fullName>DefaultCommunityPlusProfile__c</fullName>
    <label>Default Community Plus Profile</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/DefaultPermissionSet__c.field-meta.xml
<CustomField>
    <fullName>DefaultPermissionSet__c</fullName>
    <label>Default Permission Set</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DefaultCommunityProfile__c/fields/DefaultProfile__c.field-meta.xml
<CustomField>
    <fullName>DefaultProfile__c</fullName>
    <label>Default Profile</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HOT_CommunityUsersServiceTest.cls
@isTest
private class HOT_CommunityUsersServiceTest {
    @TestSetup
    private static void setup() {
        Profile communityProfile = [
            SELECT Name
            FROM Profile
            WHERE
                Name = 'Personbruker Login'
                OR Name = 'Trial Customer Portal User'
            LIMIT 1
        ];

        Profile communityPlusLoginProfile = [
            SELECT Name
            FROM Profile
            WHERE
                Name = 'Samhandler Login'
                OR Name = 'Trial Customer Portal User'
            LIMIT 1
        ];

        DefaultCommunityProfile__c defaultCommunityProfile = new DefaultCommunityProfile__c(
            DefaultProfile__c = communityProfile.Name,
            DefaultPermissionSet__c = 'CRM_ManageAsyncRequests',
            DefaultCommunityPlusProfile__c = 'Trial Customer Portal User',
            DefaultCommunityPlusPermissionSetGroup__c = 'Test',
            DefaultCommunityPlusLoginPermSet__c = 'TestCommunity',
            DefaultCommunityPlusLoginProfile__c = communityPlusLoginProfile.Name
        );
        insert defaultCommunityProfile;
    }

    @IsTest
    private static void createTjenesteleverandorFormidlerUser() {
        User officeUser = TestDataFactory_Community.getUsers(
            1,
            'System Administrator',
            true,
            true
        )[0];
        System.runAs(officeUser) {
            Person__c person = new Person__c();
            person.INT_Confidential__c = 'Ugradert';
            person.INT_FirstName__c = 'Tjenesteleverandor';
            person.INT_LastName__c = 'Formidler';
            person.Name = '01011800001';
            insert person;
        }

        Test.startTest();
        HOT_CommunityUsersService.createTjenesteleverandorFormidlerUser(
            new List<String>{ '01011800001' }
        );
        Test.stopTest();

        User user = [
            SELECT Id, Name, FirstName, LastName, ProfileId
            FROM User
            WHERE Name = 'Tjenesteleverandor Formidler'
        ];
        System.assertEquals('Tjenesteleverandor', user.FirstName);
        System.assertEquals('Formidler', user.LastName);
    }
}