force-app/IdPorten/objects/IdPortenCache__c/IdPortenCache__c.object-meta.xml
<CustomObject>
    <label>ID-porten Cache</label>
    <nameField>
        <label>SID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ID-porten Cache</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/IdPorten/objects/IdPortenCache__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Session</fullName>
            </value>
            <value>
                <fullName>Code Verifier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/IdPorten/classes/IdPortenLogoutRestService_Test.cls
@IsTest
private class IdPortenLogoutRestService_Test {
   
    @TestSetup
    static void makeData(){
        IdPortenCache__c cache=new IdPortenCache__c();    
        cache.Name='sid';
        cache.UserId__c='0051j000009na8sAAA';
        cache.Type__c='Session';
        insert cache;
    }

    @IsTest
    private static void testLogoutBySessionId_whenSidInCache(){
        IdPortenLogoutRestService.logoutBySessionId('sid');
        system.assertEquals(0,[SELECT COUNT() FROM IdPortenCache__c WHERE Name='sid'], 'Cache is found and deleted');
    }

    @IsTest
    private static void testLogoutBySessionId_whenSidDoNotExistInCache(){
        IdPortenLogoutRestService.logoutBySessionId('sid2');
        system.assertEquals(1,[SELECT COUNT() FROM IdPortenCache__c WHERE Name='sid'], 'Cache is not found and not deleted');
    }
}