force-app/IdPorten/objects/IdPortenCache__c/IdPortenCache__c.object-meta.xml
<CustomObject>
    <label>ID-porten Cache</label>
    <nameField>
        <label>SID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ID-porten Cache</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/IdPorten/objects/IdPortenCache__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Session</fullName>
            </value>
            <value>
                <fullName>Code Verifier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/IdPorten/classes/CodeVerifierRestService_Test.cls
@IsTest
private class CodeVerifierRestService_Test {
    
    @IsTest
    private static void testStoreCodeVerifier(){
        CodeVerifierRestService.storeCodeVerifier('verifier','mockState');
        System.assertEquals(1,[SELECT COUNT() FROM IdPortenCache__c WHERE Type__c='Code Verifier']);
    }

    @IsTest
    private static void testGetCodeVerifier(){
        CodeVerifierRestService.storeCodeVerifier('verifier','mockState');

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestUri = '/services/apexrest/idporten/codeverifier';
        req.addParameter('state','mockState');
            
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        String actualVerifier=CodeVerifierRestService.getCodeVerifier();
        Test.stopTest();
        
        System.assertEquals('verifier',actualVerifier);
        System.assertEquals(0,[SELECT COUNT() FROM IdPortenCache__c WHERE Type__c='Code Verifier'], 'Record is deleted');
    }
}