force-app/IdPorten/objects/IdPortenCache__c/IdPortenCache__c.object-meta.xml
<CustomObject>
    <label>ID-porten Cache</label>
    <nameField>
        <label>SID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ID-porten Cache</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/IdPorten/objects/IdPortenCache__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Session</fullName>
            </value>
            <value>
                <fullName>Code Verifier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/IdPorten/classes/IdPortenLogoutRestService.cls
@RestResource(urlMapping='/idporten/logout/*')
global class IdPortenLogoutRestService {
   
    @HttpPost
    global static void logoutBySessionId(String sid) {
        List<IdPortenCache__c> cache=[SELECT UserId__c FROM IdPortenCache__c WHERE Name=:sid AND Type__c='Session'];

        if(cache.size()>0){
            //delete users all active sessions
            delete [SELECT Id FROM AuthSession WHERE UsersId=:cache[0].UserId__c AND LoginType='Chatter Communities External User Third Party SSO'];
        }
    }
}