force-app/IdPorten/objects/IdPortenCache__c/IdPortenCache__c.object-meta.xml
<CustomObject>
    <label>ID-porten Cache</label>
    <nameField>
        <label>SID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ID-porten Cache</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/IdPorten/objects/IdPortenCache__c/fields/Nonce__c.field-meta.xml
<CustomField>
    <fullName>Nonce__c</fullName>
    <label>Nonce</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/IdPorten/objects/IdPortenCache__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/IdPorten/objects/IdPortenCache__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Session</fullName>
            </value>
            <value>
                <fullName>Code Verifier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/IdPorten/classes/CodeVerifierRestService.cls
@RestResource(urlMapping='/idporten/codeverifier/*')
global with sharing class CodeVerifierRestService {

    @HttpPost
    global static void storeCodeVerifier(String codeVerifier, String nonce, String state) {
        try{
            IdPortenCache__c cache=new IdPortenCache__c();
            cache.CodeVerifier__c=codeVerifier;
            cache.Nonce__c=nonce;
            cache.State__c=state;
            cache.Type__c='Code Verifier';
            insert cache;
        	}   
        	catch (Exception e) {
            LoggerUtility logger = new LoggerUtility();
            logger.exception(e, CRM_ApplicationDomain.Domain.NKS);
            logger.publishSynch();
        }
        
    }

    @HttpGet
    global static IdPortenCache getCodeVerifier() {
        String state = getRequestParam('state');
        for(IdPortenCache__c cache:[SELECT State__c, Nonce__c, CodeVerifier__c FROM IdPortenCache__c WHERE CreatedDate> :Datetime.now().addMinutes(-15) AND Type__c='Code Verifier' ORDER BY CreatedDate DESC]){
            if(cache.State__c==state){
                IdPortenCache idPortenCache=new IdPortenCache();
                idPortenCache.codeVerifier=cache.CodeVerifier__c;
                idportenCache.nonce=cache.Nonce__c;
                delete cache;
                return idPortenCache;
            }
        }
        //unable to find cache. Log as error
        LoggerUtility logger = new LoggerUtility();
        logger.error('Unable to find cache record ' + state,null, CRM_ApplicationDomain.Domain.NKS);
        logger.publishSynch();
        return null;
    }

    private static String getRequestParam(String paramName) {
        RestRequest request = RestContext.request;
        return request.params.containsKey(paramName) ? request.params.get(paramName) : null;
    }
}